# SVM

In [1]:
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline 

from pylearn_ml191.svm import KernelSVM
from sklearn.svm import SVC 

# Ignore warnings
import warnings 
warnings.filterwarnings("ignore")

# Fixed random seed
RANDOM_SEED = 21

In [2]:
X = np.array([[2, 1], [4, 3], [2, 5], [3, 7]])
y = np.array([[1.], [1.], [-1.], [-1.]])

### Using SVM in pylearn_ml191

In [3]:
model = KernelSVM(kernel="linear", C=0.5, atol=1e-3)
model.fit(X, y)

### Using SVC

In [4]:
svc = SVC(kernel="linear", C=0.5, tol=1e-3)
svc.fit(X, y)

SVC(C=0.5, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [5]:
# SO SÁNH NGHIỆM BẰNG CÔNG THỨC VÀ NGHIỆM ĐẠT ĐƯỢC BẰNG CVXOPT
print("--------------NGHIỆM BẰNG THƯ VIỆN SVC -------------------")
print("Support vectors: ")
print(svc.support_vectors_)
print("w:", svc.coef_)
print("b:", svc.intercept_)
print("----------------------------------------------------------")
print("----------  NGHIỆM BẰNG pylearn_ml191 ---------")
print("Support vectors: ")
print(model.support_vectors_)
print("w:", model.w)
print("b:", model.b)
print("----------------------------------------------------------")

--------------NGHIỆM BẰNG THƯ VIỆN SVC -------------------
Support vectors: 
[[2. 5.]
 [4. 3.]]
w: [[ 0.5 -0.5]]
b: [0.5]
----------------------------------------------------------
----------  NGHIỆM BẰNG pylearn_ml191 ---------
Support vectors: 
[[4 3]
 [2 5]]
w: [[ 0.49958108 -0.50031418]]
b: [0.50251346]
----------------------------------------------------------


In [6]:
X_val = np.array([[2.5, 2], [1.0, 4.5]])
model.predict(X_val)

array([[ 1.],
       [-1.]])