## Import Libraries

In [1]:
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline 

from pylearn_ml191.functional import softmax

# Ignore warnings
import warnings 
warnings.filterwarnings("ignore")

# Fixed random seed
RANDOM_SEED = 21

## Result 

In [2]:
Z = np.array([[2, 5, 6.5, 7.5], [4, 1, 3, 4], [6, 9.5, 2.5, 1.5]])
labels = ['laptop', 'chuột', 'adapter', 'mobilephone']
y_raw = ['laptop', 'chuột', 'adapter']

# Label Encoder 
y = np.zeros((3, 4))
for i, y_ in enumerate(y_raw):
    cls = labels.index(y_)
    y[i][cls] = 1
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [3]:
# a. Predict 
y_hat = softmax(Z)
print(y_hat)

[[2.81061039e-03 5.64526187e-02 2.53003084e-01 6.87733687e-01]
 [4.13621976e-01 2.05930256e-02 1.52163022e-01 4.13621976e-01]
 [2.92767829e-02 9.69513899e-01 8.84082240e-04 3.25235680e-04]]


In [4]:
# b. Loss 
L = -np.sum(y*np.log(y_hat))
print(L)

16.788116890151976


In [5]:
# c. 
dz = (y_hat - y).T
print(dz)

[[-9.97189390e-01  4.13621976e-01  2.92767829e-02]
 [ 5.64526187e-02 -9.79406974e-01  9.69513899e-01]
 [ 2.53003084e-01  1.52163022e-01 -9.99115918e-01]
 [ 6.87733687e-01  4.13621976e-01  3.25235680e-04]]
